#修改端口
server:
    port: 80

#数据库配置
spring: # 冒号后面加空格
  datasource: 
    url: jdbc:mysql://bj-cdb-pjv7dxwz.sql.tencentcdb.com:63620/lumber?autoReconnect=true
    username: jcl
    password: 088113jclJCL
    driver-class-name: com.mysql.jdbc.Driver
   